///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SuppliersListModelDataSuppliersSupplierStaff {
/*
{
  "_id": "5f1a9c45cce33f65397fa7ea",
  "role": "5f1a9c45cce33f65397fa7ec",
  "email": "bakingkuptest@gmail.com",
  "mobileNumber": "966500017340",
  "firstName": "jalal",
  "lastName": "dweickat",
  "type": "Supplier",
  "__v": 0,
  "language": "en",
  "deleted": false,
  "createdAt": "2020-08-30T18:19:41.620Z",
  "isStaff": false,
  "invitesByCustomer": false,
  "invitedBy": "Das",
  "status": "Active"
}
*/

  String Id;
  String role;
  String email;
  String mobileNumber;
  String firstName;
  String lastName;
  String type;
  int v;
  String language;
  bool deleted;
  String createdAt;
  bool isStaff;
  bool invitesByCustomer;
  String invitedBy;
  String status;

  SuppliersListModelDataSuppliersSupplierStaff({
    this.Id,
    this.role,
    this.email,
    this.mobileNumber,
    this.firstName,
    this.lastName,
    this.type,
    this.v,
    this.language,
    this.deleted,
    this.createdAt,
    this.isStaff,
    this.invitesByCustomer,
    this.invitedBy,
    this.status,
  });
  SuppliersListModelDataSuppliersSupplierStaff.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    role = json['role']?.toString();
    email = json['email']?.toString();
    mobileNumber = json['mobileNumber']?.toString();
    firstName = json['firstName']?.toString();
    lastName = json['lastName']?.toString();
    type = json['type']?.toString();
    v = json['__v']?.toInt();
    language = json['language']?.toString();
    deleted = json['deleted'];
    createdAt = json['createdAt']?.toString();
    isStaff = json['isStaff'];
    invitesByCustomer = json['invitesByCustomer'];
    invitedBy = json['invitedBy']?.toString();
    status = json['status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['role'] = role;
    data['email'] = email;
    data['mobileNumber'] = mobileNumber;
    data['firstName'] = firstName;
    data['lastName'] = lastName;
    data['type'] = type;
    data['__v'] = v;
    data['language'] = language;
    data['deleted'] = deleted;
    data['createdAt'] = createdAt;
    data['isStaff'] = isStaff;
    data['invitesByCustomer'] = invitesByCustomer;
    data['invitedBy'] = invitedBy;
    data['status'] = status;
    return data;
  }
}

class SuppliersListModelDataSuppliersSupplier {
/*
{
  "_id": "5f1a9c45cce33f65397fa7eb",
  "representativeName": "baking up",
  "createdAt": "2020-07-24T11:31:01.522Z",
  "status": "Active",
  "paymentInterval": "Month",
  "paymentFrequency": 1,
  "creditLimit": 3000,
  "staff": [
    {
      "_id": "5f1a9c45cce33f65397fa7ea",
      "role": "5f1a9c45cce33f65397fa7ec",
      "email": "bakingkuptest@gmail.com",
      "mobileNumber": "966500017340",
      "firstName": "jalal",
      "lastName": "dweickat",
      "type": "Supplier",
      "__v": 0,
      "language": "en",
      "deleted": false,
      "createdAt": "2020-08-30T18:19:41.620Z",
      "isStaff": false,
      "invitesByCustomer": false,
      "invitedBy": "Das",
      "status": "Active"
    }
  ]
}
*/

  String Id;
  String representativeName;
  String createdAt;
  String status;
  String paymentInterval;
  int paymentFrequency;
  int creditLimit;
  List<SuppliersListModelDataSuppliersSupplierStaff> staff;

  SuppliersListModelDataSuppliersSupplier({
    this.Id,
    this.representativeName,
    this.createdAt,
    this.status,
    this.paymentInterval,
    this.paymentFrequency,
    this.creditLimit,
    this.staff,
  });
  SuppliersListModelDataSuppliersSupplier.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    representativeName = json['representativeName']?.toString();
    createdAt = json['createdAt']?.toString();
    status = json['status']?.toString();
    paymentInterval = json['paymentInterval']?.toString();
    paymentFrequency = json['paymentFrequency']?.toInt();
    creditLimit = json['creditLimit']?.toInt();
    if (json['staff'] != null) {
      final v = json['staff'];
      final arr0 = <SuppliersListModelDataSuppliersSupplierStaff>[];
      v.forEach((v) {
        arr0.add(SuppliersListModelDataSuppliersSupplierStaff.fromJson(v));
      });
      staff = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['representativeName'] = representativeName;
    data['createdAt'] = createdAt;
    data['status'] = status;
    data['paymentInterval'] = paymentInterval;
    data['paymentFrequency'] = paymentFrequency;
    data['creditLimit'] = creditLimit;
    if (staff != null) {
      final v = staff;
      final arr0 = [];
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data['staff'] = arr0;
    }
    return data;
  }
}

class SuppliersListModelDataSuppliers {
/*
{
  "supplier": {
    "_id": "5f1a9c45cce33f65397fa7eb",
    "representativeName": "baking up",
    "createdAt": "2020-07-24T11:31:01.522Z",
    "status": "Active",
    "paymentInterval": "Month",
    "paymentFrequency": 1,
    "creditLimit": 3000,
    "staff": [
      {
        "_id": "5f1a9c45cce33f65397fa7ea",
        "role": "5f1a9c45cce33f65397fa7ec",
        "email": "bakingkuptest@gmail.com",
        "mobileNumber": "966500017340",
        "firstName": "jalal",
        "lastName": "dweickat",
        "type": "Supplier",
        "__v": 0,
        "language": "en",
        "deleted": false,
        "createdAt": "2020-08-30T18:19:41.620Z",
        "isStaff": false,
        "invitesByCustomer": false,
        "invitedBy": "Das",
        "status": "Active"
      }
    ]
  },
  "balance": -3719.1,
  "remainingTillLimit": 2865.45,
  "paymentDue": "2022-01-24T14:31:01.522Z",
  "relationStatus": "Active"
}
*/

  SuppliersListModelDataSuppliersSupplier supplier;
  double balance;
  double remainingTillLimit;
  String paymentDue;
  String relationStatus;

  SuppliersListModelDataSuppliers({
    this.supplier,
    this.balance,
    this.remainingTillLimit,
    this.paymentDue,
    this.relationStatus,
  });
  SuppliersListModelDataSuppliers.fromJson(Map<String, dynamic> json) {
    supplier = (json['supplier'] != null) ? SuppliersListModelDataSuppliersSupplier.fromJson(json['supplier']) : null;
    balance = json['balance']?.toDouble();
    remainingTillLimit = json['remainingTillLimit']?.toDouble();
    paymentDue = json['paymentDue']?.toString();
    relationStatus = json['relationStatus']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (supplier != null) {
      data['supplier'] = supplier.toJson();
    }
    data['balance'] = balance;
    data['remainingTillLimit'] = remainingTillLimit;
    data['paymentDue'] = paymentDue;
    data['relationStatus'] = relationStatus;
    return data;
  }
}

class SuppliersListModelData {
/*
{
  "suppliers": [
    {
      "supplier": {
        "_id": "5f1a9c45cce33f65397fa7eb",
        "representativeName": "baking up",
        "createdAt": "2020-07-24T11:31:01.522Z",
        "status": "Active",
        "paymentInterval": "Month",
        "paymentFrequency": 1,
        "creditLimit": 3000,
        "staff": [
          {
            "_id": "5f1a9c45cce33f65397fa7ea",
            "role": "5f1a9c45cce33f65397fa7ec",
            "email": "bakingkuptest@gmail.com",
            "mobileNumber": "966500017340",
            "firstName": "jalal",
            "lastName": "dweickat",
            "type": "Supplier",
            "__v": 0,
            "language": "en",
            "deleted": false,
            "createdAt": "2020-08-30T18:19:41.620Z",
            "isStaff": false,
            "invitesByCustomer": false,
            "invitedBy": "Das",
            "status": "Active"
          }
        ]
      },
      "balance": -3719.1,
      "remainingTillLimit": 2865.45,
      "paymentDue": "2022-01-24T14:31:01.522Z",
      "relationStatus": "Active"
    }
  ],
  "count": 1
}
*/

  List<SuppliersListModelDataSuppliers> suppliers;
  int count;

  SuppliersListModelData({
    this.suppliers,
    this.count,
  });
  SuppliersListModelData.fromJson(Map<String, dynamic> json) {
    if (json['suppliers'] != null) {
      final v = json['suppliers'];
      final arr0 = <SuppliersListModelDataSuppliers>[];
      v.forEach((v) {
        arr0.add(SuppliersListModelDataSuppliers.fromJson(v));
      });
      suppliers = arr0;
    }
    count = json['count']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (suppliers != null) {
      final v = suppliers;
      final arr0 = [];
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data['suppliers'] = arr0;
    }
    data['count'] = count;
    return data;
  }
}

class SuppliersListModel {
/*
{
  "status": "Success",
  "errorCode": 0,
  "data": {
    "suppliers": [
      {
        "supplier": {
          "_id": "5f1a9c45cce33f65397fa7eb",
          "representativeName": "baking up",
          "createdAt": "2020-07-24T11:31:01.522Z",
          "status": "Active",
          "paymentInterval": "Month",
          "paymentFrequency": 1,
          "creditLimit": 3000,
          "staff": [
            {
              "_id": "5f1a9c45cce33f65397fa7ea",
              "role": "5f1a9c45cce33f65397fa7ec",
              "email": "bakingkuptest@gmail.com",
              "mobileNumber": "966500017340",
              "firstName": "jalal",
              "lastName": "dweickat",
              "type": "Supplier",
              "__v": 0,
              "language": "en",
              "deleted": false,
              "createdAt": "2020-08-30T18:19:41.620Z",
              "isStaff": false,
              "invitesByCustomer": false,
              "invitedBy": "Das",
              "status": "Active"
            }
          ]
        },
        "balance": -3719.1,
        "remainingTillLimit": 2865.45,
        "paymentDue": "2022-01-24T14:31:01.522Z",
        "relationStatus": "Active"
      }
    ],
    "count": 1
  }
}
*/

  String status;
  int errorCode;
  SuppliersListModelData data;

  SuppliersListModel({
    this.status,
    this.errorCode,
    this.data,
  });
  SuppliersListModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toString();
    errorCode = json['errorCode']?.toInt();
    data = (json['data'] != null) ? SuppliersListModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['errorCode'] = errorCode;
    if (data != null) {
      data['data'] = this.data.toJson();
    }
    return data;
  }
}

