///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BranchesModelDataLocation {
/*
{
  "address": "Dose Cafe | دوز كافيه | BURAYDAH, Buraydah Saudi Arabia",
  "city": "BURAYDAH",
  "coordinates": [
    26.3997555
  ],
  "type": "point"
}
*/

  String address;
  String city;
  List<double> coordinates;
  String type;

  BranchesModelDataLocation({
    this.address,
    this.city,
    this.coordinates,
    this.type,
  });
  BranchesModelDataLocation.fromJson(Map<String, dynamic> json) {
    address = json['address']?.toString();
    city = json['city']?.toString();
    if (json['coordinates'] != null) {
      final v = json['coordinates'];
      final arr0 = <double>[];
      v.forEach((v) {
        arr0.add(v.toDouble());
      });
      coordinates = arr0;
    }
    type = json['type']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['address'] = address;
    data['city'] = city;
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
      v.forEach((v) {
        arr0.add(v);
      });
      data['coordinates'] = arr0;
    }
    data['type'] = type;
    return data;
  }
}

class BranchesModelData {
/*
{
  "_id": "5fc2ae05db42124d33ee8a57",
  "customer": "5f4d264122c0291c7f2e5fc2",
  "createdAt": "2020-11-28T23:07:33.358Z",
  "__v": 0,
  "location": {
    "address": "Dose Cafe | دوز كافيه | BURAYDAH, Buraydah Saudi Arabia",
    "city": "BURAYDAH",
    "coordinates": [
      26.3997555
    ],
    "type": "point"
  },
  "branchName": "Dose BURAYDAH",
  "status": "Active"
}
*/

  String Id;
  String customer;
  String createdAt;
  int v;
  BranchesModelDataLocation location;
  String branchName;
  String status;
bool isSelected ;
  BranchesModelData({
    this.Id,
    this.customer,
    this.createdAt,
    this.v,
    this.location,
    this.branchName,
    this.status,
    this.isSelected =false ,
  });
  BranchesModelData.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    customer = json['customer']?.toString();
    createdAt = json['createdAt']?.toString();
    v = json['__v']?.toInt();
    location = (json['location'] != null) ? BranchesModelDataLocation.fromJson(json['location']) : null;
    branchName = json['branchName']?.toString();
    status = json['status']?.toString();
    isSelected =false ;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['customer'] = customer;
    data['createdAt'] = createdAt;
    data['__v'] = v;
    if (location != null) {
      data['location'] = location.toJson();
    }
    data['branchName'] = branchName;
    data['status'] = status;
    data['isSelected'] = false;
    return data;
  }
}

class BranchesModel {
/*
{
  "status": "Success",
  "errorCode": 0,
  "data": [
    {
      "_id": "5fc2ae05db42124d33ee8a57",
      "customer": "5f4d264122c0291c7f2e5fc2",
      "createdAt": "2020-11-28T23:07:33.358Z",
      "__v": 0,
      "location": {
        "address": "Dose Cafe | دوز كافيه | BURAYDAH, Buraydah Saudi Arabia",
        "city": "BURAYDAH",
        "coordinates": [
          26.3997555
        ],
        "type": "point"
      },
      "branchName": "Dose BURAYDAH",
      "status": "Active"
    }
  ]
}
*/

  String status;
  int errorCode;
  List<BranchesModelData> data;

  BranchesModel({
    this.status,
    this.errorCode,
    this.data,
  });
  BranchesModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toString();
    errorCode = json['errorCode']?.toInt();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <BranchesModelData>[];
      v.forEach((v) {
        arr0.add(BranchesModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['errorCode'] = errorCode;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}

